apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster2-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Moon-5070/gitops.git
    targetRevision: main
    path: apps/cluster2-nginx
  destination:
    server: https://192.168.160.15:6443
    namespace: nginx-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
