apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster2-nginx
  labels:
    app: cluster2-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster2-nginx
  template:
    metadata:
      labels:
        app: cluster2-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
