apiVersion: v1
kind: Service
metadata:
  name: cluster2-nginx
  labels:
    app: cluster2-nginx
spec:
  type: ClusterIP
  selector:
    app: cluster2-nginx
  ports:
    - port: 80
      targetPort: 80
